apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod

spec:
  containers:
  - name: two-tier-app-container
    image: mruday033/flaskapp:latest
    ports:
    - containerPort: 5000

    env:
    - name: DB_HOST
      value: "mysql"
    - name: DB_PORT
      value: "3306"
    - name: DB_NAME
      value: "mydb"
    - name: DB_USER
      value: "root"
    - name: DB_PASSWORD
      value: "root"